<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Rose Glow Nail Polish',
                'slug' => 'rose-glow-nail-polish',
                'category' => 'nail polish',
                'description' => 'Kutek warna rose glow dengan finishing glossy tahan lama.',
                'stock' => 120,
                'price' => 75000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1763801854.jpg',
                'rating' => 4.5,
                'review_count' => 48,
            ],
            [
                'name' => 'Precision Nail Tools Kit',
                'slug' => 'precision-nail-tools-kit',
                'category' => 'nail tools',
                'description' => 'Set peralatan manicure profesional untuk perawatan kuku sehari-hari.',
                'stock' => 80,
                'price' => 125000,
                'discount' => 5,
                'status' => 'published',
                'image' => 'images/products/1764160971.jpg',
                'rating' => 4.7,
                'review_count' => 27,
            ],
            [
                'name' => 'Vitamin Cuticle Oil',
                'slug' => 'vitamin-cuticle-oil',
                'category' => 'nail care',
                'description' => 'Minyak kutikula dengan vitamin E untuk menutrisi kuku agar tidak kering.',
                'stock' => 150,
                'price' => 55000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764164122.jpg',
                'rating' => 4.3,
                'review_count' => 19,
            ],
            [
                'name' => 'Complete Nail Art Kit',
                'slug' => 'complete-nail-art-kit',
                'category' => 'nail kit',
                'description' => 'Paket lengkap nail art dengan kuas, glitter, dan stiker dekoratif.',
                'stock' => 60,
                'price' => 185000,
                'discount' => 15,
                'status' => 'published',
                'image' => 'images/products/1764164312.jpg',
                'rating' => 4.8,
                'review_count' => 34,
            ],

            // --- Tambahan produk fixed untuk kebutuhan tim ---
            [
                'name' => 'Aurora Chrome Gel Polish',
                'slug' => 'aurora-chrome-gel-polish',
                'category' => 'nail polish',
                'description' => 'Gel polish efek chrome aurora untuk tampilan glam.',
                'stock' => 45,
                'price' => 99000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1764164483.jpg',
                'rating' => 4.6,
                'review_count' => 52,
            ],
            [
                'name' => 'Pastel Sky Nail Polish',
                'slug' => 'pastel-sky-nail-polish',
                'category' => 'nail polish',
                'description' => 'Warna pastel lembut untuk gaya sehari-hari.',
                'stock' => 110,
                'price' => 65000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764164652.jpg',
                'rating' => 4.2,
                'review_count' => 21,
            ],
            [
                'name' => 'Midnight Plum Nail Polish',
                'slug' => 'midnight-plum-nail-polish',
                'category' => 'nail polish',
                'description' => 'Warna plum gelap untuk look elegan di malam hari.',
                'stock' => 15,
                'price' => 72000,
                'discount' => 5,
                'status' => 'low stock',
                'image' => 'images/products/1764164665.jpg',
                'rating' => 4.4,
                'review_count' => 13,
            ],
            [
                'name' => 'Glitter Top Coat',
                'slug' => 'glitter-top-coat',
                'category' => 'nail polish',
                'description' => 'Top coat dengan glitter halus untuk hasil mengkilap.',
                'stock' => 70,
                'price' => 85000,
                'discount' => 15,
                'status' => 'published',
                'image' => 'images/products/1764164766.jpg',
                'rating' => 4.7,
                'review_count' => 39,
            ],
            [
                'name' => 'Quick-Dry Base Coat',
                'slug' => 'quick-dry-base-coat',
                'category' => 'nail polish',
                'description' => 'Base coat cepat kering untuk mempercepat manicure.',
                'stock' => 0,
                'price' => 78000,
                'discount' => 0,
                'status' => 'draft',
                'image' => 'images/products/1764296177.jpg',
                'rating' => 0.0,
                'review_count' => 0,
            ],
            [
                'name' => 'Satin Nude Gel Polish',
                'slug' => 'satin-nude-gel-polish',
                'category' => 'nail polish',
                'description' => 'Gel polish nude satin untuk tampilan minimalis.',
                'stock' => 95,
                'price' => 105000,
                'discount' => 20,
                'status' => 'published',
                'image' => 'images/products/1764296265.jpg',
                'rating' => 4.9,
                'review_count' => 88,
            ],
            [
                'name' => 'Ocean Teal Nail Polish',
                'slug' => 'ocean-teal-nail-polish',
                'category' => 'nail polish',
                'description' => 'Warna teal segar untuk look yang standout.',
                'stock' => 65,
                'price' => 69000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1766201673.jpg',
                'rating' => 4.3,
                'review_count' => 22,
            ],
            [
                'name' => 'Velvet Red Nail Polish',
                'slug' => 'velvet-red-nail-polish',
                'category' => 'nail polish',
                'description' => 'Merah velvet klasik untuk acara spesial.',
                'stock' => 8,
                'price' => 79000,
                'discount' => 10,
                'status' => 'low stock',
                'image' => 'images/products/1766201946.jpg',
                'rating' => 4.6,
                'review_count' => 15,
            ],


            [
                'name' => 'Stainless Cuticle Nipper',
                'slug' => 'stainless-cuticle-nipper',
                'category' => 'nail tools',
                'description' => 'Tang kutikula stainless, presisi, dan awet.',
                'stock' => 35,
                'price' => 145000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1764400071.jpg',
                'rating' => 4.5,
                'review_count' => 44,
            ],
            [
                'name' => 'Crystal Nail File Set',
                'slug' => 'crystal-nail-file-set',
                'category' => 'nail tools',
                'description' => 'Set nail file untuk membentuk kuku lebih rapi.',
                'stock' => 140,
                'price' => 60000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764405051.jpg',
                'rating' => 4.1,
                'review_count' => 17,
            ],
            [
                'name' => 'Precision Nail Brush',
                'slug' => 'precision-nail-brush',
                'category' => 'nail tools',
                'description' => 'Kuas nail art ukuran kecil untuk detail halus.',
                'stock' => 9,
                'price' => 45000,
                'discount' => 5,
                'status' => 'low stock',
                'image' => 'images/products/1764409108.jpg',
                'rating' => 4.3,
                'review_count' => 8,
            ],
            [
                'name' => 'UV Gel Lamp 48W',
                'slug' => 'uv-gel-lamp-48w',
                'category' => 'nail tools',
                'description' => 'Lampu UV 48W untuk curing gel polish lebih cepat.',
                'stock' => 20,
                'price' => 325000,
                'discount' => 25,
                'status' => 'published',
                'image' => 'images/products/1764409138.jpg',
                'rating' => 4.8,
                'review_count' => 61,
            ],
            [
                'name' => 'Nail Buffer Block',
                'slug' => 'nail-buffer-block',
                'category' => 'nail tools',
                'description' => 'Buffer block untuk menghaluskan permukaan kuku.',
                'stock' => 160,
                'price' => 25000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764409157.jpg',
                'rating' => 4.0,
                'review_count' => 12,
            ],
            [
                'name' => 'Manicure Tool Pouch',
                'slug' => 'manicure-tool-pouch',
                'category' => 'nail tools',
                'description' => 'Pouch untuk menyimpan tools manicure agar rapi.',
                'stock' => 5,
                'price' => 70000,
                'discount' => 0,
                'status' => 'draft',
                'image' => 'images/products/1764470369.jpg',
                'rating' => 0.0,
                'review_count' => 0,
            ],
            [
                'name' => 'Cuticle Pusher (Stainless)',
                'slug' => 'cuticle-pusher-stainless',
                'category' => 'nail tools',
                'description' => 'Pendorong kutikula stainless untuk hasil rapi.',
                'stock' => 90,
                'price' => 35000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1766537193.jpg',
                'rating' => 4.2,
                'review_count' => 19,
            ],
            [
                'name' => 'Nail Clippers Pro Set',
                'slug' => 'nail-clippers-pro-set',
                'category' => 'nail tools',
                'description' => 'Set gunting kuku pro untuk manicure rumahan.',
                'stock' => 22,
                'price' => 88000,
                'discount' => 15,
                'status' => 'published',
                'image' => 'images/products/1766537212.jpg',
                'rating' => 4.5,
                'review_count' => 26,
            ],

            [
                'name' => 'Keratin Nail Strengthener',
                'slug' => 'keratin-nail-strengthener',
                'category' => 'nail care',
                'description' => 'Perawatan kuku dengan keratin untuk mengurangi kuku rapuh.',
                'stock' => 75,
                'price' => 98000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1764470505.jpg',
                'rating' => 4.6,
                'review_count' => 29,
            ],
            [
                'name' => 'Vitamin E Cuticle Balm',
                'slug' => 'vitamin-e-cuticle-balm',
                'category' => 'nail care',
                'description' => 'Balm kutikula untuk menjaga kelembapan dan kilau alami.',
                'stock' => 105,
                'price' => 52000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764470520.jpg',
                'rating' => 4.2,
                'review_count' => 16,
            ],
            [
                'name' => 'Gentle Nail Cleanser',
                'slug' => 'gentle-nail-cleanser',
                'category' => 'nail care',
                'description' => 'Cleanser lembut untuk membersihkan kuku sebelum polish.',
                'stock' => 25,
                'price' => 65000,
                'discount' => 5,
                'status' => 'low stock',
                'image' => 'images/products/1764470533.jpg',
                'rating' => 4.1,
                'review_count' => 7,
            ],
            [
                'name' => 'Nail Repair Serum',
                'slug' => 'nail-repair-serum',
                'category' => 'nail care',
                'description' => 'Serum untuk membantu memperbaiki kuku yang pecah dan kusam.',
                'stock' => 55,
                'price' => 115000,
                'discount' => 15,
                'status' => 'published',
                'image' => 'images/products/1764472353.jpg',
                'rating' => 4.7,
                'review_count' => 33,
            ],
            [
                'name' => 'Hydrating Hand & Nail Cream',
                'slug' => 'hydrating-hand-and-nail-cream',
                'category' => 'nail care',
                'description' => 'Krim tangan dan kuku agar tetap lembut dan terhidrasi.',
                'stock' => 0,
                'price' => 89000,
                'discount' => 0,
                'status' => 'draft',
                'image' => 'images/products/1764472389.jpg',
                'rating' => 0.0,
                'review_count' => 0,
            ],
            [
                'name' => 'Nail Surface Dehydrator',
                'slug' => 'nail-surface-dehydrator',
                'category' => 'nail care',
                'description' => 'Dehydrator untuk persiapan sebelum gel/polish.',
                'stock' => 40,
                'price' => 75000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1766537232.jpg',
                'rating' => 4.4,
                'review_count' => 23,
            ],
            [
                'name' => 'Nail Primer (Acid-Free)',
                'slug' => 'nail-primer-acid-free',
                'category' => 'nail care',
                'description' => 'Primer acid-free untuk daya rekat lebih baik.',
                'stock' => 18,
                'price' => 82000,
                'discount' => 5,
                'status' => 'low stock',
                'image' => 'images/products/1766537254.jpg',
                'rating' => 4.5,
                'review_count' => 11,
            ],
            [
                'name' => 'Soothing Cuticle Remover',
                'slug' => 'soothing-cuticle-remover',
                'category' => 'nail care',
                'description' => 'Cuticle remover lembut untuk perawatan rutin.',
                'stock' => 120,
                'price' => 58000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1766537357.jpg',
                'rating' => 4.1,
                'review_count' => 14,
            ],
            [
                'name' => 'Nail Care Travel Set',
                'slug' => 'nail-care-travel-set',
                'category' => 'nail care',
                'description' => 'Set travel: oil, balm, dan mini file.',
                'stock' => 0,
                'price' => 99000,
                'discount' => 0,
                'status' => 'draft',
                'image' => 'images/products/1766537438.jpg',
                'rating' => 0.0,
                'review_count' => 0,
            ],

            [
                'name' => 'Beginner Manicure Starter Kit',
                'slug' => 'beginner-manicure-starter-kit',
                'category' => 'nail kit',
                'description' => 'Paket pemula: file, buffer, cuticle pusher, dan oil.',
                'stock' => 40,
                'price' => 165000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1764472424.jpg',
                'rating' => 4.4,
                'review_count' => 24,
            ],
            [
                'name' => 'Nail Art Sticker Mega Pack',
                'slug' => 'nail-art-sticker-mega-pack',
                'category' => 'nail kit',
                'description' => 'Sticker nail art berbagai motif untuk kreasi cepat.',
                'stock' => 200,
                'price' => 45000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1764472458.jpg',
                'rating' => 4.3,
                'review_count' => 41,
            ],
            [
                'name' => 'Chrome Powder Essentials Kit',
                'slug' => 'chrome-powder-essentials-kit',
                'category' => 'nail kit',
                'description' => 'Kit chrome powder untuk hasil mirror/metallic.',
                'stock' => 12,
                'price' => 175000,
                'discount' => 20,
                'status' => 'low stock',
                'image' => 'images/products/1764513289.jpg',
                'rating' => 4.8,
                'review_count' => 18,
            ],
            [
                'name' => 'Salon Pro Nail Kit',
                'slug' => 'salon-pro-nail-kit',
                'category' => 'nail kit',
                'description' => 'Paket lengkap untuk kebutuhan nail artist rumahan.',
                'stock' => 30,
                'price' => 295000,
                'discount' => 15,
                'status' => 'published',
                'image' => 'images/products/1764663083.jpg',
                'rating' => 4.9,
                'review_count' => 57,
            ],
            [
                'name' => 'Seasonal Glitter Collection Kit',
                'slug' => 'seasonal-glitter-collection-kit',
                'category' => 'nail kit',
                'description' => 'Koleksi glitter musiman untuk desain festive.',
                'stock' => 0,
                'price' => 155000,
                'discount' => 0,
                'status' => 'draft',
                'image' => 'images/products/1764667649.jpg',
                'rating' => 0.0,
                'review_count' => 0,
            ],
            [
                'name' => 'French Tips Starter Kit',
                'slug' => 'french-tips-starter-kit',
                'category' => 'nail kit',
                'description' => 'Kit french tips: guide, brush, dan top coat.',
                'stock' => 48,
                'price' => 175000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1766537492.jpg',
                'rating' => 4.4,
                'review_count' => 20,
            ],
            [
                'name' => 'Builder Gel Essentials Kit',
                'slug' => 'builder-gel-essentials-kit',
                'category' => 'nail kit',
                'description' => 'Kit builder gel untuk memperkuat dan membentuk kuku.',
                'stock' => 10,
                'price' => 235000,
                'discount' => 15,
                'status' => 'low stock',
                'image' => 'images/products/1766537603.jpg',
                'rating' => 4.7,
                'review_count' => 12,
            ],
            [
                'name' => 'Minimalist Nude Sticker Kit',
                'slug' => 'minimalist-nude-sticker-kit',
                'category' => 'nail kit',
                'description' => 'Sticker nude minimalis untuk desain cepat.',
                'stock' => 160,
                'price' => 42000,
                'discount' => 0,
                'status' => 'published',
                'image' => 'images/products/1766537672.jpg',
                'rating' => 4.2,
                'review_count' => 27,
            ],
            [
                'name' => 'Nail Art Brush Set (8 pcs)',
                'slug' => 'nail-art-brush-set-8-pcs',
                'category' => 'nail kit',
                'description' => 'Set kuas nail art 8 pcs untuk berbagai teknik.',
                'stock' => 32,
                'price' => 120000,
                'discount' => 10,
                'status' => 'published',
                'image' => 'images/products/1766547039.jpg',
                'rating' => 4.6,
                'review_count' => 31,
            ],
            [
                'name' => 'Glitter & Foil Combo Kit',
                'slug' => 'glitter-and-foil-combo-kit',
                'category' => 'nail kit',
                'description' => 'Kit kombinasi glitter dan foil untuk aksen premium.',
                'stock' => 14,
                'price' => 145000,
                'discount' => 20,
                'status' => 'low stock',
                'image' => 'images/products/1766547115.jpg',
                'rating' => 4.8,
                'review_count' => 25,
            ],
        ];

        foreach ($products as $product) {
            $slug = $product['slug'] ?? Str::slug($product['name']);

            Product::updateOrCreate(
                ['slug' => $slug],
                array_merge($product, ['slug' => $slug])
            );
        }
    }
}
